language: python
install:
 - "python bootstrap.py --distribute"
 - "./bin/buildout --distribute"
 - "sudo apt-get install -y openjdk-6-jdk openjdk-6-source openjdk-6-demo openjdk-6-doc openjdk-6-jre-headless openjdk-6-jre-lib git-core ant1.8 zip unzip"
 - "curl http://dl.google.com/android/android-sdk_r20.0.1-linux.tgz | tar -xf -"
 - "pwd"
 - "cd android-sdk-linux && pwd"
env:
 - ANDROID_HOME=android-sdk-linux
python:
   - "2.7"
script:
  - ./bin/robotframework -L TRACE --monitorwidth 65 tests/

